export const LISTROOMLOCATION_REQUEST = 'LISTROOMLOCATION_REQUEST'
export const LISTROOMLOCATION_SUCCESS = 'LISTROOMLOCATION_SUCCESS'
export const LISTROOMLOCATION_ERROR = 'LISTROOMLOCATION_ERROR'

export const UPLOAD_IMAGEROOM = 'UPLOAD_IMAGEROOM'

export const DELETE_ROOM = 'DELETE_ROOM'
