export const LOCATION_REQUEST = 'LOCATION_REQUEST'
export const LOCATION_SUCCESS = 'LOCATION_SUCCESS'
export const LOCATION_ERROR = 'LOCATION_ERROR'

export const SEARCH_LOCATION = 'SEARCH_LOCATION'

export const CREATE_LOCATION = 'CREATE_LOCATION'

export const UPDATE_LOCATION = 'UPDATE_LOCATION'

export const DELETE_LOCATION = 'DELETE_LOCATION'

export const UPLOADPHOTO_LOCATION = 'UPLOAD_LOCATION'