export const MODALVISIBLE1_SHOW = 'MODALVISIBLE1_SHOW'
export const MODALVISIBLE1_HIDE = 'MODALVISIBLE1_HIDE'

export const MODALVISIBLE2_SHOW = 'MODALVISIBLE2_SHOW'
export const MODALVISIBLE2_HIDE = 'MODALVISIBLE2_HIDE'