export const RIVIEWROOM_REQUEST = 'RIVIEWROOM_REQUEST'
export const RIVIEWROOM_SUCCESS = 'RIVIEWROOM_SUCCESS'
export const RIVIEWROOM_ERROR = 'RIVIEWROOM_ERROR'

export const CREATE_REVIEW = 'CREATE_REVIEW'

export const UPDATE_REVIEW = 'UPDATE_REVIEW'


export const DELETE_REVIEW = 'DELETE_REVIEW'