export const ROOMDETAIL_REQUEST = 'ROOMDETAIL_REQUEST'
export const ROOMDETAIL_SUCCESS = 'ROOMDETAIL_SUCCESS'
export const ROOMDETAIL_ERROR = 'ROOMDETAIL_ERROR'

export const BOOKING_ROOM = 'BOOKING_ROOM'

export const CREATE_ROOM = 'CREATE_ROOM'

export const SEARCH_ROOM = 'SEARCH_ROOM'

export const UPDATE_ROOM = 'UPDATE_ROOM'