export const USERPAGINATION_REQUEST = 'USERPAGINATION_REQUEST'
export const USERPAGINATION_SUCCESS = 'USERPAGINATION_SUCCESS'
export const USERPAGINATION_ERROR = 'USERPAGINATION_ERROR'

export const SEARCH_USER = 'SEARCH_USER'

export const DELETE_USER = 'DELETE_USER'

export const ADD_USER = 'ADD_USER'

export const UPDATE_USER = 'UPDATE_USER'